In [73]:
import numpy as np

In [1]:
import tensorflow as tf
print(tf. __version__)

2.9.1


In [2]:
scalar=tf.constant(4)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
#Check the number of dimensions of a tensor(ndim stands for number of dimensions)
scalar.ndim


0

In [7]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10])>

In [8]:
vector.ndim

1

In [10]:
#Create a matrix
matrix=tf.constant([[10,7],
                   [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
matrix.ndim

2

In [16]:
#Create another matrix
an_matrix=tf.constant([[10.,7.],
                      [3.,2,],
                      [5.,6.]], dtype=tf.float16)
an_matrix
#higher the number of precision higher the number is stored on the computer

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  6.]], dtype=float16)>

an_matrix

In [17]:
an_matrix.ndim

2

In [18]:
 #dimension=shape-1

In [19]:
tensor=tf.constant([
                     [
                      [1,2,3],
                      [4,5,6]
                      ],
                   [
                    [7,8,9],
                    [10,11,12]
                   ],
                    [
                     [13,14,15],
                     [16,17,18]
                    ]
                    ])

In [21]:
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])>

In [22]:
tensor.ndim

3

In [29]:
#Scalar: a Single number
#VECTOR: a number with direction
#MATRIX: a 2-dimension array of numbers
#TENSOR: a n-d array of numbers (where n can be any number, a 0-dimension tensor is a scalar, a 1-D tensor is a vector)
    

In [34]:
#Create tensor with varisble
changeable_tensor=tf.Variable([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7])>

In [35]:
#changing elements in changeable tensor
changeable_tensor[0]=7

TypeError: 'ResourceVariable' object does not support item assignment

In [36]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7])>

In [41]:
unchangeable_tensor=tf.constant([50,7])
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([50,  7])>

In [42]:
#changing elements in unchangeable tensor
unchangeable_tensor[0].assign(5)
unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [55]:
#Creating Random Tensors : tensors of some arbitrary size with random tensors
random_1=tf.random.Generator.from_seed(42)#set seed for reproducibility
random_1=random_1.normal(shape=(3,2))

In [56]:
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [61]:
#Shuffle a tensor (valueable when you want)
not_shuffled=tf.constant([[10,7],[3,4],[2,5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [62]:
not_shuffled.ndim

2

In [68]:
#Shuffle non shuffled tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]])>

In [76]:
numpy_A= np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [80]:
A= tf.constant(numpy_A, shape=(2,3,4))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])>)

In [83]:
#TENSOR ATTRIBUTES: GETTING INFORMATION LIKE:SHAPE, RANK, AXIS/DIMENSION, SIZE
tf.zeros([3, 4], tf.int32)

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])>

In [85]:
tf.ones([3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [87]:
#CREATE A RAANK 4 TENSOR
rank_4_tensor=tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [88]:
rank_4_tensor[0] #0th axis

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [89]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [93]:
#Getting attributes of our tensor
print("Datatypes of every element:", rank_4_tensor.dtype)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along 0-axis:", rank_4_tensor.shape[0])
print("Elements along the lasst axis:", rank_4_tensor.shape[-1])
print("Total number of elements in tensor:", tf.size(rank_4_tensor))
print("Total number of elements in tensor:", tf.size(rank_4_tensor).numpy())

Datatypes of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0-axis: 2
Elements along the lasst axis: 5
Total number of elements in tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in tensor: 120


In [94]:
 #Indexing
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>